### ISSUE TITLE
Hey Aitzaz Imtiaz

### ISSUE THREAD

**Issue by JeffTheK** [AristodamusAdairs/Aristo-Framework#1]
Would you mind if I convert your code to support python 3.0?

**Comment by JeffTheK** [comment]
I also want to improve the framework overall

**Comment by AristodamusAdairs** [comment]
sure bruh

**Comment by AristodamusAdairs** [comment]
PR me, I will accept it with close eyes,

**Comment by JeffTheK** [comment]
Thank you. I will continue converting it to python 3.0

**Comment by AristodamusAdairs** [comment]
your pleasures, thanks for supporting my codes

**Comment by AristodamusAdairs** [comment]
@JeffTheK Bruh, I am starting editing files with your name with mine.
If possible please do it for myself and PR me. It is mean to use my name when you got a significant contribution.
